### ISSUE TITLE
[Doc]: Missing `grep`

### ISSUE THREAD

**Issue by AviRubin** [HabanaAI/vllm-fork#355]
### 📚 The doc issue

The step `pip list | habana` could be better by adding `grep`

### Suggest a potential alternative/fix

`pip list | habana` could be `pip list | grep habana` to make the steps easier to execute and maintain consistency with the previous step of `apt list --installed | grep habana`

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by michalkuligowski** [comment]
Fixed in #144
