### ISSUE TITLE
[Installation]: habana_main branch installation fails on 1.17 driver and firmware.

### ISSUE THREAD

**Issue by MohitIntel** [HabanaAI/vllm-fork#380]
### Your current environment

 HL-SMI Version:  hl-1.17.0-fw-51.3.0 
 Driver Version:    1.17.0-28a11ca

### How you are installing vllm

```sh
$ git clone https://github.com/HabanaAI/vllm-fork.git
$ cd vllm-fork
$ git checkout habana_main
$ pip install -e .
```

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by MohitIntel** [comment]
Suggest the README_GAUDI installation instructions be updated to below:

$ git clone https://github.com/HabanaAI/vllm-fork.git
$ cd vllm-fork
$ git checkout **v0.5.3.post1-Gaudi-1.17.0**
$ pip install -e .

**Comment by michalkuligowski** [comment]
Fixed in release notes. Add update to release procedure
