### ISSUE TITLE
[Installation]: v0.5.3.post1+Gaudi-1.18.0 has unknown manifest with 2.4.1 pytorch image

### ISSUE THREAD

**Issue by vbedida79** [HabanaAI/vllm-fork#450]
### Your current environment

```text
The output of `python collect_env.py`
```

### How you are installing vllm

We are using `v0.5.3.post1+Gaudi-1.18.0` and image https://github.com/HabanaAI/vllm-fork/blob/v0.5.3.post1%2BGaudi-1.18.0/Dockerfile.hpu to run a sample Vllm server with Gaudi on OpenShift 

The image `vault.habana.ai/gaudi-docker/1.18.0/ubuntu22.04/habanalabs/pytorch-installer-2.4.1:latest` used in Dockerfile.hpu does not exist [24.04 link](https://vault.habana.ai/ui/native/gaudi-docker/1.18.0/ubuntu24.04/habanalabs/) and [22.04 link](https://vault.habana.ai/ui/native/gaudi-docker/1.18.0/ubuntu22.04/habanalabs/). Hence image build fails with manifest unknown.
The instructions in release tag (Run Docker image) https://github.com/HabanaAI/vllm-fork/releases/tag/v0.5.3.post1%2BGaudi-1.18.0 also point to this image instead of 2.4.0. 

This is updated with 2.4.0 image in main branch, but not the latest release v0.5.3.post1+Gaudi-1.18.0. 

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by michalkuligowski** [comment]
This will be fixed in 1.18.2

**Comment by uMartinXu** [comment]
@michalkuligowski Great to know that!
Could you let us know when 1.18.2 will be released? :-)
